# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieTest
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SDWebImage'
  pod 'JGProgressHUD'
  pod 'ESPullToRefresh'
  pod 'Wormholy', :configurations => ['Debug']

  target 'MovieTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieTestUITests' do
    # Pods for testing
  end

end
